"""
Notification System Module

Sends alerts to configured channels (Discord webhook, Slack, generic HTTP POST,
and email via SMTP) when a monitored target changes between scans.

Reads config from environment variables:
    NOTIFY_WEBHOOK_URL   — Discord / generic webhook URL
    NOTIFY_SLACK_URL     — Slack incoming webhook URL
    NOTIFY_EMAIL_TO      — recipient address(es), comma-separated
    NOTIFY_EMAIL_FROM    — sender address (defaults to SMTP_USER)
    SMTP_HOST            — SMTP server hostname
    SMTP_PORT            — SMTP port (default 587)
    SMTP_USER            — SMTP login username
    SMTP_PASS            — SMTP login password
    SMTP_TLS             — "1"/"true" to enable STARTTLS (default: enabled)
"""
from __future__ import annotations

import os
import logging
import smtplib
import datetime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Any

import requests

logger = logging.getLogger("osint.notifier")


# ── Internal helpers ──────────────────────────────────────────────────────────

def _env(key: str, default: str = "") -> str:
    """Return stripped env var value or default."""
    return os.getenv(key, default).strip()


def _bool_env(key: str, default: bool = True) -> bool:
    """Return bool interpretation of an env var."""
    val = _env(key).lower()
    if val in ("0", "false", "no", "off"):
        return False
    if val in ("1", "true", "yes", "on"):
        return True
    return default


# ── Public helpers ────────────────────────────────────────────────────────────

def send_webhook(url: str, payload: dict) -> bool:
    """
    POST JSON payload to a webhook URL.

    Args:
        url:     Full webhook URL (Discord, generic HTTP endpoint, etc.)
        payload: Dict to serialise as JSON body

    Returns:
        True on HTTP 2xx, False on any error.
    """
    if not url:
        logger.debug("send_webhook: no URL provided")
        return False
    try:
        resp = requests.post(
            url,
            json=payload,
            timeout=10,
            headers={"Content-Type": "application/json", "User-Agent": "OSINT-Tool/notifier"},
        )
        if resp.status_code < 300:
            logger.debug("Webhook delivered → %s (%d)", url[:60], resp.status_code)
            return True
        logger.warning("Webhook returned %d for %s", resp.status_code, url[:60])
        return False
    except Exception as exc:
        logger.error("Webhook error (%s): %s", url[:60], exc)
        return False


def send_slack(url: str, target: str, summary: str) -> bool:
    """
    Send a Slack-formatted Block-Kit message via an incoming webhook.

    Args:
        url:     Slack incoming webhook URL
        target:  The OSINT target identifier
        summary: Plain-text summary of changes / findings

    Returns:
        True on success, False on error.
    """
    if not url:
        logger.debug("send_slack: no URL provided")
        return False

    payload: dict[str, Any] = {
        "blocks": [
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": f"OSINT Alert — {target}",
                    "emoji": True,
                },
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": summary,
                },
            },
            {
                "type": "context",
                "elements": [
                    {
                        "type": "mrkdwn",
                        "text": (
                            f"_Generated by OSINT-Tool · "
                            f"{datetime.datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}_"
                        ),
                    }
                ],
            },
        ]
    }
    return send_webhook(url, payload)


def send_email(target: str, summary: str) -> bool:
    """
    Send a notification email via SMTP using settings from environment.

    Reads: NOTIFY_EMAIL_TO, NOTIFY_EMAIL_FROM, SMTP_HOST, SMTP_PORT,
           SMTP_USER, SMTP_PASS, SMTP_TLS

    Args:
        target:  Target identifier shown in the subject line
        summary: Plain-text body content

    Returns:
        True on success, False on any error or missing config.
    """
    smtp_host = _env("SMTP_HOST")
    smtp_user = _env("SMTP_USER")
    smtp_pass = _env("SMTP_PASS")
    to_raw    = _env("NOTIFY_EMAIL_TO")

    if not smtp_host or not to_raw:
        logger.debug("send_email: SMTP_HOST or NOTIFY_EMAIL_TO not configured")
        return False

    smtp_port = int(_env("SMTP_PORT") or "587")
    use_tls   = _bool_env("SMTP_TLS", default=True)
    from_addr = _env("NOTIFY_EMAIL_FROM") or smtp_user
    to_addrs  = [a.strip() for a in to_raw.split(",") if a.strip()]

    subject = f"[OSINT-Tool] Change detected: {target}"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = from_addr
    msg["To"]      = ", ".join(to_addrs)
    msg["X-Mailer"] = "OSINT-Tool/notifier"

    plain_part = MIMEText(summary, "plain", "utf-8")
    html_body = (
        "<html><body style='font-family:monospace;background:#0d1117;color:#e6edf3;padding:20px'>"
        f"<h2 style='color:#58a6ff'>OSINT Alert — {target}</h2>"
        f"<pre style='background:#161b22;padding:12px;border-radius:6px'>{summary}</pre>"
        "<p style='color:#8b949e;font-size:0.8em'>OSINT-Tool &middot; automated notification</p>"
        "</body></html>"
    )
    html_part = MIMEText(html_body, "html", "utf-8")

    msg.attach(plain_part)
    msg.attach(html_part)

    try:
        if use_tls:
            server = smtplib.SMTP(smtp_host, smtp_port, timeout=15)
            server.ehlo()
            server.starttls()
            server.ehlo()
        else:
            server = smtplib.SMTP_SSL(smtp_host, smtp_port, timeout=15)

        if smtp_user and smtp_pass:
            server.login(smtp_user, smtp_pass)

        server.sendmail(from_addr, to_addrs, msg.as_string())
        server.quit()
        logger.info("Email sent to %s for target '%s'", to_addrs, target)
        return True

    except smtplib.SMTPException as exc:
        logger.error("SMTP error for '%s': %s", target, exc)
        return False
    except OSError as exc:
        logger.error("Network error sending email for '%s': %s", target, exc)
        return False


# ── Summary builder ───────────────────────────────────────────────────────────

def _build_summary(target: str, modules: list, data: dict) -> str:
    """
    Build a concise plain-text summary of key findings from scan data.

    Highlights IPs, open ports, CVEs, and breach information.

    Args:
        target:  The scanned target
        modules: List of modules that were run
        data:    Combined scan data dict

    Returns:
        Multi-line string suitable for webhook / email bodies.
    """
    lines: list[str] = [
        f"Target  : {target}",
        f"Modules : {', '.join(modules) if modules else '—'}",
        f"Time    : {datetime.datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
        "",
    ]

    # IP / Geo
    ip_data = data.get("ip", {})
    geo = ip_data.get("geo", {}).get("data", {})
    if geo.get("query"):
        lines.append(
            f"IP      : {geo['query']}  ({geo.get('country', '')} / {geo.get('org', '')})"
        )

    # Open ports
    shodan = ip_data.get("shodan", {})
    if shodan.get("ports"):
        lines.append(f"Ports   : {', '.join(str(p) for p in shodan['ports'][:20])}")

    # CVEs
    vulns = shodan.get("vulns", [])
    if vulns:
        suffix = "..." if len(vulns) > 5 else ""
        lines.append(f"CVEs    : {', '.join(vulns[:5])}{suffix}")

    # Breaches (email module)
    hibp = data.get("email", {}).get("hibp", {})
    breaches = hibp.get("breaches", []) or []
    if breaches:
        names = ", ".join(b.get("name", "?") for b in breaches[:5])
        suffix = "..." if len(breaches) > 5 else ""
        lines.append(f"Breaches: {len(breaches)} found — {names}{suffix}")
    else:
        # Fallback: breach_check module
        total = data.get("breach", {}).get("summary", {}).get("total_breaches", 0)
        if total:
            lines.append(f"Breaches: ~{total} total (see full report)")

    # Secrets
    secrets = data.get("secrets", {}).get("findings", []) or []
    if secrets:
        high = sum(1 for f in secrets if f.get("severity") in ("HIGH", "CRITICAL"))
        lines.append(f"Secrets : {len(secrets)} found ({high} high/critical)")

    # Subdomains
    sub_found = data.get("subdomains", {}).get("found", [])
    if sub_found:
        lines.append(f"Subdomns: {len(sub_found)} discovered")

    # Username profiles
    username_found = data.get("username", {}).get("found", [])
    if username_found:
        platforms = ", ".join(r.get("platform", "?") for r in username_found[:6])
        lines.append(f"Username: found on {len(username_found)} platform(s) — {platforms}")

    if len(lines) == 4:  # only header block + blank line
        lines.append("No notable findings in this scan.")

    return "\n".join(lines)


# ── Core notify function ──────────────────────────────────────────────────────

def notify_change(
    target: str,
    old_hash: str,
    new_hash: str,
    modules_run: list[str],
    data: dict,
) -> dict:
    """
    Send notifications about a detected change to all configured channels.

    Reads channel config from environment variables:
        NOTIFY_WEBHOOK_URL, NOTIFY_SLACK_URL, NOTIFY_EMAIL_TO

    Args:
        target:      The OSINT target that was scanned
        old_hash:    Previous data fingerprint (16-char hex)
        new_hash:    New data fingerprint (16-char hex)
        modules_run: Names of modules that produced data
        data:        Combined scan results dict

    Returns:
        {"sent": [channel, ...], "errors": [channel, ...]}
    """
    summary = _build_summary(target, modules_run, data)
    change_line = f"Change  : {old_hash or '(new)'} → {new_hash}"
    full_summary = f"{change_line}\n{summary}"

    sent:   list[str] = []
    errors: list[str] = []

    # Discord / generic webhook
    webhook_url = _env("NOTIFY_WEBHOOK_URL")
    if webhook_url:
        discord_payload: dict[str, Any] = {
            "username": "OSINT-Tool",
            "embeds": [
                {
                    "title": f"Change detected: {target}",
                    "description": f"```\n{full_summary}\n```",
                    "color": 0x58A6FF,
                    "footer": {"text": "OSINT-Tool · automated alert"},
                    "timestamp": datetime.datetime.utcnow().isoformat(),
                }
            ],
        }
        if send_webhook(webhook_url, discord_payload):
            sent.append("webhook")
        else:
            errors.append("webhook")

    # Slack
    slack_url = _env("NOTIFY_SLACK_URL")
    if slack_url:
        if send_slack(slack_url, target, f"```\n{full_summary}\n```"):
            sent.append("slack")
        else:
            errors.append("slack")

    # Email
    if _env("NOTIFY_EMAIL_TO") and _env("SMTP_HOST"):
        if send_email(target, full_summary):
            sent.append("email")
        else:
            errors.append("email")

    if not sent and not errors:
        logger.debug("notify_change: no notification channels configured")

    logger.info(
        "Notifications for '%s': sent=%s errors=%s",
        target, sent, errors,
    )
    return {"sent": sent, "errors": errors}


# ── Test helper ───────────────────────────────────────────────────────────────

def test_notifications() -> dict:
    """
    Send a test message to every configured notification channel.

    Returns:
        {"sent": [...], "errors": [...]} — same shape as notify_change()
    """
    logger.info("Sending test notifications to all configured channels")
    return notify_change(
        target="test-target",
        old_hash="00000000",
        new_hash="ffffffff",
        modules_run=["whois", "ip", "email"],
        data={
            "ip": {
                "geo": {
                    "data": {
                        "query": "1.2.3.4",
                        "country": "Test",
                        "org": "AS12345 TestOrg",
                    }
                },
                "shodan": {"ports": [80, 443, 8080], "vulns": []},
            },
            "email": {
                "hibp": {
                    "breaches": [
                        {
                            "name": "TestBreach",
                            "date": "2024-01-01",
                            "pwn_count": 1000,
                        }
                    ]
                }
            },
        },
    )
